version: 2.1
orbs:
  node: 'circleci/node@3.0.0'
jobs:
  test:
    docker:
      - image: circleci/node:13.12.0
    steps:
      - checkout
      - node/install:
          node-version: '13.12.0'
          npm-version: '6.14.4'
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run unit tests
          command: npm test
workflows:
  test:
    jobs:
      - test
